project:
  type: book
  output-dir: _book
  execute-dir: project
  
editor:
  render-on-save: true

book:
  title: "Linux-CB"
  author: "Martin Frigaard"
  description: |
    A Linux Cookbook
  search: true
  site-url: https://mjfrigaard.github.io/linux-cb/
  repo-url: https://github.com/mjfrigaard/linux-cb
  #repo-branch: main
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd 
    - preface.qmd
    - part_one.qmd
    - part: setups.qmd
      chapters:
        - vms.qmd
        - shells.qmd
        - terminals.qmd
    - part: basics.qmd
      chapters:
        - dirs.qmd
        - files.qmd
        - sys.qmd
    - part: syntax.qmd
      chapters:
        - commands.qmd
        - arguments.qmd
        - options.qmd
        - pipes.qmd
        - vars.qmd
    - part: text.qmd
      chapters:
        - symbols_patterns.qmd
        - text_commands.qmd
        - text_editors.qmd
    - part: scripts.qmd
      chapters:
        - format.qmd
        - permissions.qmd
    - part_two.qmd
    - part: maintenance.qmd
      chapters:
        - installs.qmd
    - part: performance.qmd
      chapters:
        - file_size.qmd
  appendices:
        - syntax_ref.qmd
        - data.qmd
        - fish.qmd
        - macos.qmd
        - quarto.qmd
        - glossary.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    date: last-modified
    date-format: iso
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#02577A"
    code-overflow: scroll
    number-sections: false
    callout-appearance: simple 
    #callout-icon: false
    code-link: false
    code-annotations: hover
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    dpi: 320
    df-print: kable
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.25
    fig-width: 7
    fig-height: 5
    engine: knitr
    mermaid:
      theme: default

execute:
  freeze: true
